Repository Silmathoron/mpl_chord_diagram, pull requests merged in 2020-11, with the labels that each got.

#15 Fix name rotation between 180 and 210 degrees
  chord_diagram.py
Labels: bugfix

#14 [chord_diagram] optionally hide zero-width chords
  chord_diagram.py
Labels: behavior-change, enhancement

#20 Update docstring and Readme
  README.md
  chord_diagram.py
Labels: documentation, enhancement
